package:
  name: k8s-tools
  version: 1.24.3
  description: "kubernetes tools"
  target-architecture:
    - all
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - binutils
      - binutils-aarch64-none-elf
      - busybox
      - ca-certificates-bundle
      - curl
pipeline:
  - runs: ./download.sh
  - runs: sha256sum -c DIGESTS
  - runs: |
      strip *-amd64
      aarch64-none-elf-strip *-arm64
  - runs: |
      ARCH=$(uname -m)
      case $ARCH in
        "x86_64") ARCH="amd64" ;;
        "aarch64") ARCH="arm64" ;;
      esac
      install -D entrypoint.sh ${{targets.destdir}}/usr/bin/entrypoint.sh
      install -D helm-${ARCH} ${{targets.destdir}}/usr/bin/helm
      install -D kapp-${ARCH} ${{targets.destdir}}/usr/bin/kapp
      install -D kbld-${ARCH} ${{targets.destdir}}/usr/bin/kbld
      install -D kubectl-${ARCH} ${{targets.destdir}}/usr/bin/kubectl
      install -D kustomize-${ARCH} ${{targets.destdir}}/usr/bin/kustomize
