package:
  name: k8s-tools
  version: 0.1.0
  description: "kubernetes tools"
  target-architecture:
  - all

environment:
  contents:
    repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
    - alpine-baselayout-data
    - busybox
    - ca-certificates-bundle
    - curl

pipeline:
- runs: |
    ls -l
    pwd
    sh ./download.sh
    ARCH=$(uname -m)
    case $ARCH in
      "x86_64") ARCH="amd64" ;;
      "aarch64") ARCH="arm64" ;;
    esac
    install -D kubectl-${ARCH} ${{targets.destdir}}/usr/bin/kubectl
    install -D kustomize-${ARCH} ${{targets.destdir}}/usr/bin/kustomize
    install -D kapp-${ARCH} ${{targets.destdir}}/usr/bin/kapp
    install -D kbld-${ARCH} ${{targets.destdir}}/usr/bin/kbld
