on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
name: Create Release
concurrency: release
jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: sigstore/cosign-installer@main
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - run: |
          echo "$SIGNING_KEY" >${{ github.workspace }}/melange.rsa
          echo "$SIGNING_KEY_PUB" >${{ github.workspace }}/melange.rsa.pub
        env:
          SIGNING_KEY: ${{ secrets.MELANGE_SIGNING_KEY }}
          SIGNING_KEY_PUB: ${{ secrets.MELANGE_SIGNING_KEY_PUB }}
      - uses: chainguard-dev/actions/setup-melange@main
      - uses: chainguard-dev/actions/melange-build-pkg@main
        with:
          config: melange.yaml
          archs: x86_64,aarch64
          sign-with-key: true
          signing-key-path: ${{ github.workspace }}/melange.rsa
          keyring-append: ${{ github.workspace }}/melange.rsa.pub
          update-index: true
      - uses: distroless/actions/apko-build@main
        with:
          config: apko.yaml
          tag: distroless-k8s-test
          keyring-append: ${{ github.workspace }}/melange.rsa.pub
          archs: x86_64
      - name: load test image
        run: docker load -i output.tar
      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: distroless-k8s-test
          config: tests.yaml
      - uses: distroless/actions/apko-snapshot@main
        with:
          config: apko.yaml
          base-tag: ghcr.io/${{ github.repository }}
          keyring-append: ${{ github.workspace }}/melange.rsa.pub
          archs: x86_64,aarch64
          additional-tags: 1.24,1.24.3
